# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool: THFServices

variables:
- name: imageName
  value: 'docker.totvs.io/thf/customer-api'
steps:
- task: Docker@1
  displayName: 'Run customer-api'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: docker.totvs.io
    command: 'Run an Image'
    dockerFile: Dockerfile
    imageName: $(imageName):$(Build.BuildNumber)
    imageNamesPath: $(Build.BuildNumber)
    restartPolicy: always
    containerCommand: 'run -d --name=customer-api --restart=always --link customer-api-mongo:mongo -e REST_PORT=8200 -e MONGO_URL=mongodb://mongo:27017/customerdb -e LOG_DIR=/var/log/customer-api -e LOG_MAX_FILES=10 -e LOG_CONSOLE=true $(imageName):$(Build.BuildNumber)'

- script: |
    docker tag $(imageName):$(Build.BuildNumber) $(imageName):latest
  displayName: Tag image as LATEST
    
- task: Docker@1
  displayName: Push image TAG Build
  inputs:
    command: Push an image
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: docker.totvs.io
    imageName: $(imageName):$(Build.BuildNumber)
    dockerFile: Dockerfile
    tagMultipleImages: false
    imageNamesPath: $(Build.BuildNumber)
    qualifyImageName: false
    restartPolicy: always

- task: Docker@1
  displayName: Push image TAG Latest
  inputs:
    command: Push an image
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: docker.totvs.io
    imageName: $(imageName):latest
    dockerFile: Dockerfile
    tagMultipleImages: false
    imageNamesPath: latest
    restartPolicy: always

- script: |
      docker rmi $(imageName):$(Build.BuildNumber)
      docker rmi $(imageName):latest
  displayName: Remove images (TAG and LATEST)
